name: Build_verification
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
    
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

#     - name: checkout
#       uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle build

    - name: Cloning Test Repo
      uses: actions/checkout@v2
      with:
        repository: saumilrewari/test
        path: /Users/runner/work/calculator/calculator/test
        submodules: recursive

    - name: Checking File Exist
      uses: andstor/file-existence-action@v2
      with:
        files: "test/opsis_project, test/opsis_project/requirements.txt"
        
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo All files exists!
      
    - name: Install and Run Appium Server
      run: |
        chmod +x test/RunAppiumServer.sh
        sh test/RunAppiumServer.sh

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Installing Dependencies
      run: |
        pip3 install -r test/opsis_project/requirements.txt

    - name: Turn on Emulator and Run Test 
      uses: ReactiveCircus/android-emulator-runner@v2.27.0
      with:
        api-level: 29
        script: pytest -k="test_pass"
        
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: infocusp123@gmail.com
        password: kqsasbllftsuezid
        subject: Github Actions job result
        to: saumil@infocusp.com
        from: test indocusp
        body: Build job of ${{github.repository}} completed successfully!
